---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tempo-pv
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /tmp/tempo
---
#CLAIM

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

