server:
  port: ${API_GATEWAY_SERVER_PORT}

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}


services:
  url:
    product: ${PRODUCT_SERVICE_URL}
    order: ${ORDER_SERVICE_URL}
    inventory: ${INVENTORY_SERVICE_URL}



