server:
  port: 9000

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}


services:
  url:
    product: ${PRODUCT_SERVICE_URL}
    order: ${ORDER_SERVICE_URL}
    inventory: ${INVENTORY_SERVICE_URL}



springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/ui.html
    urls:
      - name: Product Service
        url: /aggregate/product-service/v3/api-docs
      - name: Order Service
        url: /aggregate/order-service/v3/api-docs
      - name: Inventory Service
        url: /aggregate/inventory-service/v3/api-docs
