server:
  port: 9000

cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS_FRONTEND}

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

services:
  url:
    product: ${PRODUCT_SERVICE_URL}
    order: ${ORDER_SERVICE_URL}
    inventory: ${INVENTORY_SERVICE_URL}

springdoc:
  api-docs:
    path: ${API_DOCS_PATH}
  swagger-ui:
    path: ${API_DOCS_UI_PATH}
    urls:
      - name: Product Service
        url: ${API_DOCS_URLS_PRODUCT_SERVICE}
      - name: Order Service
        url: ${API_DOCS_URLS_ORDER_SERVICE}
      - name: Inventory Service
        url: ${API_DOCS_URLS_INVENTORY_SERVICE}

management:
  health:
    circuitbreakers:
      enabled: ${CIRCUIT_BREAKERS_ENABLED}
  endpoints:
    web:
      exposure:
        include: ${ENDPOINTS_WEB_EXPOSURE_INCLUDE}
  endpoint:
    health:
      show-details: ${ENDPOINT_HEALTH_SHOW_DETAILS}

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: ${REGISTER_HEALTH_INDICATOR}
        slidingWindowType: ${SLIDING_WINDOW_TYPE}
        slidingWindowSize: ${SLIDING_WINDOW_SIZE}
        failureRateThreshold: ${FAILURE_RATE_THRESHOLD}
        waitDurationInOpenState: ${WAIT_DURATION_IN_OPEN_STATE}
        permittedNumberOfCallsInHalfOpenState: ${PERMITTED_NUMBER_OF_CALLS_IN_HALF_OPEN_STATE}
        automaticTransitionFromOpenToHalfOpenEnabled: ${AUTOMATIC_TRANSITION_FROM_OPEN_TO_HALF_OPEN_ENABLED}
        minimum-number-of-calls: ${MINIMUM_NUMBER_OF_CALLS}

  timelimiter:
    configs:
      default:
        timeout-duration: ${TIMEOUT_DURATION}

  retry:
    configs:
      default:
        max-attempts: ${MAX_ATTEMPTS}
        wait-duration: ${WAIT_DURATION_BETWEEN_ATTEMPTS}

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

  observations:
    key-values:
      application: api-gateway

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}

  loki:
    url: ${LOKI_URL}

