---
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: broker
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: kafka
    - protocol: TCP
      port: 29092
      targetPort: 29092
      name: kafka-internal
---

