
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - .docker/postgres:/data/postgres
      - ./docker/postgresql:/docker-entrypoint-initdb.d
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"

  pgadmin:
    image: dockerframework/pgadmin
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .docker/pgadmin:/database/admin/pgadmin
    ports:
      - "5050:80"