name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest

  steps:
    - name: Checkou Code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "21"

    - name: Set up Docker
      run: |
        sudo apt-get update && sudo apt-get upgrade -y
        sudo apt-get install -y docker.io

    - name: Start Docker Service
      run: |
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Check Docker Version
      run: docker --version

    - name: Navigate to project directory
      run: cd ./inventory-service/inventory-service

    - name: Format Code
      run: ./mvnw spotless:apply

    - name: Lint Code
      run: ./mvnw spotless:check

    - name: Run Tests
      run: ./mvnw test

    - name: Build Project
      run: ./mvnw clean package -DskipTests

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: target/*.jar
