server:
  port: 8081

inventory:
  service:
    url: http://inventory-service:8082

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://postgres:5432/order_service
    username: admin
    password: admin

  driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /api-docs/ui.html
  api-docs:
    path: /api-docs



