services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - .docker/data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: product-service