services:
  product-service:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - .docker/data/mongodb:/data/db
    env_file:
      - .env

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    env_file:
      - .env

