SERVER:
  PORT: ${SERVER_PORT}

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: ${MONGODB_URI}

springdoc:
  swagger-ui:
    path: /api-docs/ui.html
  api-docs:
    path: /api-docs

