name: CI/CD Pipeline order

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci_cd_pipeline:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/order-service

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Set up Docker
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y docker.io

      - name: Start Docker Service
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Check Docker Version
        run: docker --version

      - name: Navigate to project directory
        run: cd ./order-service

      - name: Format Code
        run: ./mvnw spotless:apply

      - name: Lint Code
        run: ./mvnw spotless:check

      - name: Run Tests
        run: ./mvnw test

      - name: Build Project
        run: ./mvnw clean package -DskipTests

      - name: Log in to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker Image
        #        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push $IMAGE_NAME
        run: docker push ${{ env.IMAGE_NAME }}:latest
